config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show]
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  root to: 'pages#home'
  get 'about-us', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
    member do
      get :toggle_status
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                  reject_if: lambda { |attrs|  attrs['name'].blank? }
    include Placeholder
    validates_presence_of :title, :body, :main_image, :thumb_image

    after_initialize :set_defaults

    def set_defaults
        self.main_image ||= Placeholder.image_generator(height:'600', width:'400')
        self.thumb_image ||= Placeholder.image_generator(height:'250', width:'250')
    end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
    before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
    access all:[:show, :index], user:{except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
    layout "portfolios"

    def index
        @portfolio_item = Portfolio.all
    end

    def new
        @portfolio_item = Portfolio.new
        3.times { @portfolio_item.technologies.build }
    end

    def create
        @portfolio_item = Portfolio.new(portfolio_params)
            
            respond_to do |format|
                if @portfolio_item.save
                    format.html {redirect_to portfolios_path, notice: "Your Portfolio is now live"}
                else
                    format.html {render :new}
                end
            end
    end

    def edit
    end

    def update
        @portfolio_item = Portfolio.find(params[:id])
            respond_to do |format|
                if @portfolio_item.update(portfolio_params)
                    format.html { redirect_to portfolio_path, notice: "The record is updated successfully" }
                else
                    format.html { render :edit }
                end
            end
    end

    def show
    end

    def destroy
        #Destroy/delete the record
        @portfolio_item.destroy 

        #Redirect
        respond_to do |format|
            format.html { redirect_to portfolios_path, notice: 'Record has been deleted' }
        end
    end

    private

    def portfolio_params
        params.require(:portfolio).permit(:title,
                                         :subtitle,
                                         :body,
                                         technology_attributes: [:name]
                                         )
    end

    def set_portfolio_item
        @portfolio_item =  Portfolio.find(params[:id])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_portfolio_item.html.erb
<% @portfolio_item.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body%></p>
    <%= image_tag portfolio_item.thumb_image if !portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item.id) if logged_in?(:site_admin) %>
    <%= link_to "Delete Portfolio Item", portfolio_path(portfolio_item), method: :delete, data: { confirm: "Are you sure" } if logged_in?(:site_admin) %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit your portfilio item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>
    <div class="action">
        <%= f.submit %>
    </div>
<% end %>

app/views/portfolios/index.html.erb
<h1>Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin)%>

<%= render partial: 'portfolio_item', collection: @portfolio_item %>

app/views/portfolios/new.html.erb
<h1>Create a new portfilio item</h1>

<%= form_for(@portfolio_item) do |f| %>
    <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title %>
    </div>
    <div class="field">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle %>
    </div>
    <div class="field">
        <%= f.label :body %>
        <%= f.text_area :body %>
    </div>

    <ul>
        <%= f.fields_for :technologies do |technologies_form| %>
        <li>
            <%= technologies_form.label :name %>
            <%= technologies_form.text_field :name %>
        </li>
        <% end %>
    </ul>

    <div class="action">
        <%= f.submit "Add new portfolio" %>
    </div>
<% end %>

app/views/portfolios/show.html.erb
<h1><%= @portfolio_item.title %></h1>
<em><%= @portfolio_item.subtitle %></em>
<p><%= @portfolio_item.body %></p>

<h2>Technologies Used:</h2>
<% @portfolio_item.technologies.each do |t| %>
<p><%= t.name %></p>
<% end %>